:bug: References external buttons to correct form
bigskysoftware/htmx pull request #1820
Opened 2023-09-22 08:50 UTC by ekwoka

Solves #1819 

Basically, the `form` reference was stale because it was stored outside the listener.

This also means that the form is more likely to be cleaned up since the closure no longer references the form element.

2023-09-22 18:17 UTC, Telroshan commented
Hey, could you please retarget your PR against the `dev` branch as per the [contribution guidelines](https://github.com/bigskysoftware/htmx/blob/master/CONTRIBUTING.md) ?

2023-09-22 19:45 UTC, Telroshan commented
Also, would you mind adding a test case for that specific scenario?
I'm not afraid of regressions as we already have a lot of tests about those buttons outside forms (and the test pipeline will tell), but we don't have any that tests this situation where the form gets replaced

2023-09-23 06:25 UTC, ekwoka commented
test added. It's one of the few that passes.

2023-09-23 06:29 UTC, Telroshan commented
See my review comments about the null checks, I would expect those to cause the tests issues
Tests are running fine on other PRs especially since the recent [timing issues fix](https://github.com/bigskysoftware/htmx/commit/bb5413dfd2fc5842eda7a29a1bdc53aa92e177c4) for the pipeline, so it seems unlikely to be unrelated to your changes

2023-09-23 06:36 UTC, Telroshan commented
Also please don't push code changes to the `www` directory, as it's the directory for the htmx website itself (to which tests & htmx are copied on new releases)

2023-09-23 06:40 UTC, ekwoka commented
Got it!

The feedback on the tests was just so unhelpful it was difficult to tell what was going on (and lots of difficulty actually running tests locally since the readme is out of date)

2023-09-23 06:52 UTC, Telroshan commented
> The feedback on the tests was just so unhelpful

Yeah unfortunately, every async test will throw that unhelpful `Uncaught Error: Script error. (:0)` error, I still haven't found a way to get the actual errors in the pipeline 😕 

That's where it helps to run tests locally as mentioned in [the README](https://github.com/bigskysoftware/htmx#hacking-guide), as your browser will have all the errors in the console

> since the readme is out of date

Could you elaborate on what you felt was missing from the README? Any feedback could help future contributors to find their way around!

2023-09-23 06:59 UTC, ekwoka commented
Actually running the tests in the terminal required 

```
npm run www
npm run test
```

2023-09-23 07:07 UTC, Telroshan commented
Weird, you normally shouldn't need to do that, as the [`test` npm command](https://github.com/bigskysoftware/htmx/blob/master/package.json#L28) runs tests in the `test` folder, while the [`www` npm command](https://github.com/bigskysoftware/htmx/blob/master/package.json#L31) populates the `www` directory (which you don't need to interact with unless you're adding some documentation)
What error were you getting?

2023-09-25 08:07 UTC, Telroshan commented
Btw, only the files in `www` left to remove and I'll be able to mark this PR as ready for review

2023-10-07 04:07 UTC, 1cg commented
hey @ekwoka thanks for this fix.  Do you mind walking me through it so I make sure I understand the issue?

2023-10-07 06:14 UTC, ekwoka commented
@1cg Sure thing.

Basically, buttons are only evaluated at the start (either htmx initializing or the button being added by HTMX to the page).

This means that buttons outside forms are connected to the form they can submit at a specific point in time. But if that form then is removed/readded/replaced like by htmx swapping out the form element during a submission, the buttons handler will still only reference the old form data, even though it's actually submitting the new form.

The tests should demonstrate it quite clearly.

Since the buttons outside the form do a process to label themselves as "last clicked", this was being added to the wrong forms data. So the form would submit and not capture that button's information.

Hence this PR fixes stale form references, by not evaluating the linked form on the initial load, but instead only doing that once the button is actually clicked, making the form reference absolutely up to date.

2023-10-23 08:51 UTC, ekwoka commented
Any update on this?

2023-10-26 20:46 UTC, 1cg commented
Reswapping this back into my brain now @ekwoka

2023-10-26 21:01 UTC, 1cg requested changes

2023-10-26 21:01 UTC, 1cg commented on src/htmx.js
> +            var elt = closest(evt.target, "button, input[type='submit']");
feel like the first bit of these two functions could be refactored to use a common method, maybe `findRelatedForm(elt)` that returns nothing if there is none, then the logic can be boiled down to a check and set in both.

does that make sense?

2023-10-31 22:32 UTC, merged

2023-10-31 22:33 UTC, 1cg commented
beauty!  thank you!