Handle Space before comma in Trigger Spec
bigskysoftware/htmx pull request #2903
Opened 2024-09-13 01:30 UTC by MichaelWest22

## Description
Handle any additional whitespace placed at the end of a trigger specification by ignoring it.

Corresponding issue:
#2897 

## Testing

## Checklist

* [ ] I have read the contribution guidelines
* [ ] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
  source changes)
* [ ] This is either a bugfix, a documentation update, or a new feature that has been explicitly
  approved via an issue
* [ ] I ran the test suite locally (`npm run test`) and verified that it succeeded

2024-09-13 08:32 UTC, Telroshan approved these changes

2024-09-22 16:04 UTC, alexpetros commented
yup, this is great

2024-09-25 18:17 UTC, 1cg requested changes

2024-09-25 18:17 UTC, 1cg commented on src/htmx.js
> -            consumeUntil(tokens, NOT_WHITESPACE)
I feel like this consumeUntil should remain in the loop so we support white space inside the comma separated values, no?

2024-09-25 19:12 UTC, merged