Update preload extension documentation: form preloading and preload="always"
bigskysoftware/htmx pull request #3001
Opened 2024-11-05 23:04 UTC by marisst

Pull request should be viewed together with corresponding PR in htmx-extensions repository https://github.com/bigskysoftware/htmx-extensions/pull/106

Added documentation about
- form element preloading
- `preload="always"` configuration

2024-12-10 07:35 UTC, Telroshan commented
Note: leaving this PR open & on the side until the `preload` extension gets published with the latest update (currently `2.0.1` is still the `latest` on npm, thus these new docs are not correct _yet_)

2024-12-15 08:30 UTC, Telroshan requested changes

2024-12-15 08:30 UTC, Telroshan commented on www/content/extensions/preload.md
> +This attribute can be conbined with other configuration attributes e.g. `preload="always mouseover"`.
Just a little typo then I'll merge it!

```suggestion
This attribute can be combined with other configuration attributes e.g. `preload="always mouseover"`.
```

2024-12-15 08:42 UTC, marisst commented on www/content/extensions/preload.md
> +This attribute can be conbined with other configuration attributes e.g. `preload="always mouseover"`.
Done :)

2024-12-16 08:07 UTC, Telroshan approved these changes
Nice, and thanks again for your work on the extension 😄

2024-12-16 08:07 UTC, merged

2025-10-18 13:54 UTC, pvs-stm commented
Is the link shown in https://htmx.org/extensions/preload/ correct?
`<script src="https://cdn.jsdelivr.net/npm/htmx-ext-preload@2.1.0" integrity="sha384-fkzubQiTB69M7XTToqW6tplvxAOJkqPl5JmLAbumV2EacmuJb8xEP9KnJafk/rg8" crossorigin="anonymous"></script>`

It is producing this output in console:
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/htmx-ext-preload@2.1.0' with computed SHA-384 integrity 'KKYgXDj/WvJAt1FI2JsD8OKSFwQwuHzZWo6EEPm0Yirsk7plaoACUYnv0qlxgOB7'. The resource has been blocked.`

Also, this version doesn't seem to fix the problem of the double download of contents instead of using the cache. I'm still having this exact issue: https://github.com/bigskysoftware/htmx-extensions/issues/108