add extension swap-errors
bigskysoftware/htmx pull request #626
Opened 2021-10-20 07:18 UTC by jgirardet

the `swap-errors` extension allows swapping response when HTTP Error code is returned.
It's nice way to deal with errors server-side in
It works adding the header `HX-SWAP-ERRORS` in the response.

2021-11-12 22:27 UTC, 1cg commented
@jgirardet do you think that this extension has been obviated by the new support for configuring swap behavior in the `htmx:beforeSwap` event?

2021-11-15 16:42 UTC, jgirardet commented
No I don't. This extension allows you to write less javascript where htmx:beforeSwap forces to write more JavaScript.
Since many errors are handled server side, I think it's better for htmx to support the result (with a non 200 status code) out of the box.

2022-01-14 18:33 UTC, 1cg requested changes

2022-01-14 18:33 UTC, 1cg commented on src/ext/swap-errors.js
> +      if (evt.detail.xhr.getResponseHeader("HX-SWAP-ERRORS") !== null) {
Only change I would make is to not use all caps, which is more consistent w/ other htmx headers.

2023-07-30 17:25 UTC, alexpetros commented
> This extension allows you to write less javascript where htmx:beforeSwap forces to write more JavaScript.
Since many errors are handled server side, I think it's better for htmx to support the result (with a non 200 status code) out of the box.

I agree with this, though coming up with a conceptual framework that allows configuration via attributes (instead of JS) is difficult!

We're working with this concept in #1620, so I'm going to close this PR in favor of that.

2023-07-30 17:25 UTC, closed without merging